# Chapter 2: Peaks over heat response genes

# Load libraries
library(GenomicRanges)
library(ChIPseeker)
library(clusterProfiler)
library(GenomicFeatures)
library(DESeq2)
library(ggplot2)
library(ggVennDiagram)
library(beeswarm)
library(ggdist)
library(gghalves)
library(ggpubr)
library(patchwork)

# Load in data sets
# Transcripts
gff.file <- "~/Lab Notebook/Chapter2/Data_analysis/ATAC/Amil_ref_gen/Amil_v2.01/Amil.all.maker.noseq.gff"
txdb <- makeTxDbFromGFF(gff.file, format = "gff3") 
a.millepora.txs <- transcripts(txdb)

# # Files of called peaks (MACS2 Output)
# file_paths <- c("~/Lab Notebook/Chapter2/Data_analysis/ATAC/Peak_files/AMIL_GENO_01_S1_summits.bed",
#                 "~/Lab Notebook/Chapter2/Data_analysis/ATAC/Peak_files/AMIL_GENO_02_S2_summits.bed",
#                 "~/Lab Notebook/Chapter2/Data_analysis/ATAC/Peak_files/AMIL_GENO_03_S3_summits.bed",
#                 "~/Lab Notebook/Chapter2/Data_analysis/ATAC/Peak_files/AMIL_GENO_04_S4_summits.bed")
# 
# peak.gr.list <- list()
# 
# for (file_path in file_paths) {
#   peaks <- readPeakFile(file_path)
#   peak.gr.list[[file_path]] <- peaks
# }
# 

# Load in narrowPeaks files generated by MACS2 for significant peaks
narrowpeaks_paths <- c("~/Lab Notebook/Chapter2/Data_analysis/ATAC/Peak_files/AMIL_GENO_01_S1_peaks.narrowPeak",
                       "~/Lab Notebook/Chapter2/Data_analysis/ATAC/Peak_files/AMIL_GENO_02_S2_peaks.narrowPeak",
                       "~/Lab Notebook/Chapter2/Data_analysis/ATAC/Peak_files/AMIL_GENO_03_S3_peaks.narrowPeak",
                       "~/Lab Notebook/Chapter2/Data_analysis/ATAC/Peak_files/AMIL_GENO_04_S4_peaks.narrowPeak")

narrowpeaks.gr.list <- list()

for (file_path in narrowpeaks_paths) {
  narrow.peaks <- readPeakFile(file_path)
  narrowpeaks.gr.list[[file_path]] <- narrow.peaks
}

narrowpeaks.colnames <- c("name",
                          "score",
                          "V6",
                          "signalValue", #overall enrichment in the region
                          "pValue", # -log10
                          "qValue", # -log10 FDR
                          "peak") # point-source of the peak

colnames(mcols(narrowpeaks.gr.list[[1]])) <- narrowpeaks.colnames
colnames(mcols(narrowpeaks.gr.list[[2]])) <- narrowpeaks.colnames
colnames(mcols(narrowpeaks.gr.list[[3]])) <- narrowpeaks.colnames
colnames(mcols(narrowpeaks.gr.list[[4]])) <- narrowpeaks.colnames
head(narrowpeaks.gr.list[[1]])
head(narrowpeaks.gr.list[[2]])
head(narrowpeaks.gr.list[[3]])
head(narrowpeaks.gr.list[[4]])

# Peak Annotation
peakAnno.1 <- annotatePeak(narrowpeaks.gr.list[[1]], tssRegion=c(-3000, 3000),
                           TxDb=txdb)

peakAnno.2 <- annotatePeak(narrowpeaks.gr.list[[2]], tssRegion=c(-3000, 3000),
                           TxDb=txdb)

peakAnno.3 <- annotatePeak(narrowpeaks.gr.list[[3]], tssRegion=c(-3000, 3000),
                           TxDb=txdb)

peakAnno.4 <- annotatePeak(narrowpeaks.gr.list[[4]], tssRegion=c(-3000, 3000),
                           TxDb=txdb)


# Annotated peaks data frames
peaks.df.1 <- as.data.frame(peakAnno.1@anno@elementMetadata@listData)
genomic.annotation.detail.df.1 <- peakAnno.1@detailGenomicAnnotation
peaks.df.1 <- cbind(peaks.df.1, genomic.annotation.detail.df.1)

peaks.df.2 <- as.data.frame(peakAnno.2@anno@elementMetadata@listData)
genomic.annotation.detail.df.2 <- peakAnno.2@detailGenomicAnnotation
peaks.df.2 <- cbind(peaks.df.2, genomic.annotation.detail.df.2)

peaks.df.3 <- as.data.frame(peakAnno.3@anno@elementMetadata@listData)
genomic.annotation.detail.df.3 <- peakAnno.3@detailGenomicAnnotation
peaks.df.3 <- cbind(peaks.df.3, genomic.annotation.detail.df.3)

peaks.df.4 <- as.data.frame(peakAnno.4@anno@elementMetadata@listData)
genomic.annotation.detail.df.4 <- peakAnno.4@detailGenomicAnnotation
peaks.df.4 <- cbind(peaks.df.4, genomic.annotation.detail.df.4)

# Isolate Promoter (<=1kb) separately across genotypes
 
geno.1.promoter <- filter(peaks.df.1, annotation == "Promoter (<=1kb)") # 3453

pValue_density_geno1 <- ggplot(geno.1.promoter, aes(x = pValue)) +
  geom_density(fill = "skyblue", color = "blue") +
  labs(title = "Geno 1: Density of pValue", x = "pValue", y = "Density")

hist(geno.1.promoter$score, xlim = c(0,1000), breaks = 1000)
nrow(geno.1.promoter %>% filter(score==0))

qValue_density_geno1 <- ggplot(geno.1.promoter, aes(x = qValue)) +
  geom_density(fill = "lightgreen", color = "green") +
  labs(title = "Geno 1: Density of qValue", x = "qValue", y = "Density")

score_density_geno1 <- ggplot(geno.1.promoter, aes(x = score)) +
  geom_density(fill = "violet", color = "purple") +
  labs(title = "Geno 1: Density of score", x = "score", y = "Density")

pValue_density_geno1 + qValue_density_geno1 + score_density_geno1

geno.2.promoter <- filter(peaks.df.2, annotation == "Promoter (<=1kb)") # 10540 

pValue_density_geno2 <- ggplot(geno.2.promoter, aes(x = pValue)) +
  geom_density(fill = "skyblue", color = "blue") +
  labs(title = "Geno 2: Density of pValue", x = "pValue", y = "Density")


qValue_density_geno2 <- ggplot(geno.2.promoter, aes(x = qValue)) +
  geom_density(fill = "lightgreen", color = "green") +
  labs(title = "Geno 2: Density of qValue", x = "qValue", y = "Density")

score_density_geno2 <- ggplot(geno.2.promoter, aes(x = score)) +
  geom_density(fill = "violet", color = "purple") +
  labs(title = "Geno 2: Density of score", x = "score", y = "Density")

pValue_density_geno2 + qValue_density_geno2 + score_density_geno2

geno.3.promoter <- filter(peaks.df.3, annotation == "Promoter (<=1kb)") # 1274

pValue_density_geno3 <- ggplot(geno.3.promoter, aes(x = pValue)) +
  geom_density(fill = "skyblue", color = "blue") +
  labs(title = "Geno 3: Density of pValue", x = "pValue", y = "Density")


qValue_density_geno3 <- ggplot(geno.3.promoter, aes(x = qValue)) +
  geom_density(fill = "lightgreen", color = "green") +
  labs(title = "Geno 3: Density of qValue", x = "qValue", y = "Density")

score_density_geno3 <- ggplot(geno.3.promoter, aes(x = score)) +
  geom_density(fill = "violet", color = "purple") +
  labs(title = "Geno 3: Density of score", x = "score", y = "Density")

pValue_density_geno3 + qValue_density_geno3 + score_density_geno3

geno.4.promoter <- filter(peaks.df.4, annotation == "Promoter (<=1kb)") # 3080

pValue_density_geno4 <- ggplot(geno.4.promoter, aes(x = pValue)) +
  geom_density(fill = "skyblue", color = "blue") +
  labs(title = "Geno 4: Density of pValue", x = "pValue", y = "Density")


qValue_density_geno4 <- ggplot(geno.4.promoter, aes(x = qValue)) +
  geom_density(fill = "lightgreen", color = "green") +
  labs(title = "Geno 4: Density of qValue", x = "qValue", y = "Density")

# qValue_vs_pValue_geno4 <- ggplot(geno.4.promoter, aes(x = qValue, y = pValue)) +
#   geom_point() +
#   labs(title = "qvalue vs pvalue", x = "qValue", y = "pValue")

score_density_geno4 <- ggplot(geno.4.promoter, aes(x = score)) +
  geom_density(fill = "violet", color = "purple") +
  labs(title = "Geno 4: Density of score", x = "score", y = "Density")

# qValue_vs_score_geno4 <- ggplot(geno.4.promoter, aes(x = qValue, y = score)) +
#   geom_point() +
#   labs(title = "qValue vs score", x = "qValue", y = "score")

pValue_density_geno4 + qValue_density_geno4 + score_density_geno4
# 
# 
# # Venn Diagram 
# 
# 
# 
# geno.1.promoter <- filter(geno.1.promoter, pValue >= fdr.threshold) 
# genes.geno.1 <- unique(data.frame(gene = geno.1.promoter$geneId)) 
# genes.geno.1$geno<- as.factor("1")
# dim(genes.geno.1) #1785
# 
# 
# geno.2.promoter <- filter(geno.2.promoter, qValue >= fdr.threshold) 
# genes.geno.2 <- unique(data.frame(gene = geno.2.promoter$geneId))
# genes.geno.2$geno<- as.factor("2")
# dim(genes.geno.2) #7898
# 
# geno.3.promoter <- filter(geno.3.promoter, qValue >= fdr.threshold) #759 promoters with peak score greater than the first quartile
# genes.geno.3 <- unique(data.frame(gene = geno.3.promoter$geneId))
# genes.geno.3$geno<- as.factor("3")
# dim(genes.geno.3) #721
# 
# geno.4.promoter <- filter(geno.4.promoter, qValue >= fdr.threshold) #1984 promoters with peak score greater than the first quartile
# genes.geno.4 <- unique(data.frame(gene = geno.4.promoter$geneId))
# genes.geno.4$geno<- as.factor("4")
# dim(genes.geno.4) #1859
# 
# x <- list(
#   Geno_1 = genes.geno.1$gene, 
#   Geno_2 = genes.geno.2$gene, 
#   Geno_3 = genes.geno.3$gene,
#   Geno_4 = genes.geno.4$gene
# )
# ggVennDiagram(x)
# 
# # Select genes that appear in at all 4 genos:
# peaks.intersection.all.genos <- Reduce(intersect, x)

# Visualize the accessible regions and the expression in the control samples 
file.dir <- "/Users/tillandsia/Lab Notebook/Chapter2/Data_analysis/TagSeq/Gene_count_files/"
my.files <- grep(".txt", list.files(file.dir), value=TRUE)
my.metadata <- read.table("/Users/tillandsia/Lab Notebook/Chapter2/Data_analysis/TagSeq/tag_seq_meta_data.txt", header = TRUE)

# Create sample table
sampleNames <- c("01_27_Y","01_28_R","01_40_Y","01_42_R","01_45_Y","01_46_Y",
                 "01_51_Y","01_52_Y","01_54_Y","01_58_Y","01_63_Y","01_68_Y",
                 "01_78_R","01_92_Y","02_29_Y","02_34_Y","02_35_R","02_47_Y",
                 "02_65_R","02_79_R","03_29_R","03_48_Y","03_62_R","03_72_R",
                 "03_90_Y","03_91_R","04_48_R","04_65_Y","04_70_Y","04_95_Y",
                 "05_43_R","05_46_R","05_50_Y","05_62_Y","05_82_Y","05_88_R",
                 "06_22_Y","06_32_R","06_59_R","06_64_R","06_67_R","06_72_Y",
                 "06_82_R","06_92_R","07_31_R","07_36_R","07_39_R","07_53_Y",
                 "07_64_Y","07_88_Y","08_19_R","08_30_R","08_33_Y","08_36_Y",
                 "08_45_R","08_50_R","08_85_Y","08_95_R")

my.sampleTable <- data.frame(sampleName = sampleNames, 
                             fileName = my.files, 
                             condition = my.metadata[,2:10])

# Convert variables to factors
factorVars <- c("condition.acclimation.temp", "condition.acclimation.class", "condition.acclimation.txt",
                "condition.stress.txt", "condition.stress.group", 
                "condition.stress.day", "condition.ext.date",
                "condition.ext.batch", "condition.genotype")


my.sampleTable[, factorVars] <- lapply(my.sampleTable[, factorVars], factor)
colnames(my.sampleTable)

# Check my.sampleTable
my.sampleTable

## Look at only control sample heat stress genes since acclimation can dampen the ge response
non.acclimated.files.list <- filter(my.metadata, acclimation.class == "control")[,11]

# Filter metadata and create sample table
fil.metadata <- filter(my.metadata, acclimation.class == "control")
non.acc.sampleNames <- fil.metadata$ID

non.acclimated.sampleTable <- data.frame(
  sampleName = non.acc.sampleNames,
  fileName = non.acclimated.files.list,
  condition = fil.metadata[,2:10]
)

# Convert factors in the sample table
columns_to_factorize <- c("condition.acclimation.temp", 
                          "condition.stress.txt",
                          "condition.ext.batch",
                          "condition.genotype")

for (column in columns_to_factorize) {
  non.acclimated.sampleTable[[column]] <- factor(non.acclimated.sampleTable[[column]])
}


# Create DESeqDataSet
non_acclimated_ddsHTSeq <- DESeqDataSetFromHTSeqCount(
  sampleTable = non.acclimated.sampleTable,
  directory = file.dir,
  design = ~ condition.stress.txt
)

# Filter low count rows
nonacc.keep <- rowSums(counts(non_acclimated_ddsHTSeq)) >= 10
non_acclimated_ddsHTSeq <- non_acclimated_ddsHTSeq[nonacc.keep,]
non.acc.dds <- DESeq(non_acclimated_ddsHTSeq)
non.acc.expression.df <- as.data.frame(results(non.acc.dds)) # Note:log2 fold change (MLE): condition.stress.txt 36 vs 24.5 
non.acc.expression.df <- non.acc.expression.df[non.acc.expression.df$padj < 0.05, ]

# Add peak data to non.acc.expression.df:
## 1st: TRUE or FALSE for if peaks are shared across all genotypes
in.peaks.all.genos <- rownames(non.acc.expression.df) %in% peaks.intersection.all.genos 

# Ground truth calls
true_genes <- non.acc.expression.df[in.peaks.all.genos, ]

# Assign TRUE/FALSE values based on presence in peaks.intersection.all.genos
non.acc.expression.df$all.genos <- in.peaks.all.genos

# Visualize
non.acc.expression.df$all.genos <- factor(non.acc.expression.df$all.genos)
filtered.non.acc.expression.df <- non.acc.expression.df[non.acc.expression.df$baseMean <= 20000,]
non.acc.expression.df$log10bM <- log10(non.acc.expression.df$baseMean)

if (any(non.acc.expression.df$baseMean <= 0)) {
  warning("Zero or negative values detected in baseMean column.")
}

# Filter out zero or negative values from baseMean
non.acc.expression.df <- non.acc.expression.df[non.acc.expression.df$baseMean > 0, ]

# Perform logarithm transformation
non.acc.expression.df$log10bM <- log10(non.acc.expression.df$baseMean)
non.acc.expression.df <- non.acc.expression.df[!is.na(non.acc.expression.df$log10bM), ]

# Check for NA values in log10bM
if (any(is.na(non.acc.expression.df$log10bM))) {
  warning("NA values detected in log10bM column.")
}


# Log10 Base mean expression of genes with accessible promoters
ggplot(non.acc.expression.df, aes(x = all.genos, 
                                  y = log10bM, 
                                  fill = all.genos)) + 
  stat_dotsinterval(side = "bottom", 
                    slab_linewidth = NA) +
  scale_fill_manual(values = c("#b5e2fa",
                               "#ed6a5a")) +
  labs(title = "Log10 base mean expression of genes with\naccessible and non-accessible promoters",
       x = "Accessible promoter (≤ 1 kb)") +
  theme_pubr() + 
  stat_compare_means(method = "wilcox.test",
                     comparisons = list(c("TRUE", "FALSE")),
                     label = "p.format",
                     step.increase = 0.05) +
  theme(legend.position = "none") 

# log2FC to heat stress of genes with accessible promoters
ggplot(non.acc.expression.df, aes(x = all.genos, 
                                  y = log2FoldChange, 
                                  fill = all.genos)) + 
  stat_dotsinterval(side = "bottom", 
                    slab_linewidth = NA) +
  scale_fill_manual(values = c("#b5e2fa",
                               "#ed6a5a")) +
  labs(title = "Gene log2FC in response to heat stress with\naccessible and non-accessible promoters",
       x = "Accessible promoter (≤ 1 kb)") +
  theme_pubr() + 
  stat_compare_means(method = "t.test", 
                     comparisons = list(c("TRUE", "FALSE")),
                     label = "p.format",
                     step.increase = 0.05) +
  theme(legend.position = "none") 



# lfcSE of accessible promoters
ggplot(non.acc.expression.df, aes(x = all.genos, 
                                  y = lfcSE, 
                                  fill = all.genos)) + 
  stat_dotsinterval(side = "bottom", 
                    slab_linewidth = NA) +
  scale_fill_manual(values = c("#b5e2fa",
                               "#ed6a5a")) +
  labs(title = "Gene expression variation with\naccessible and non-accessible promoters",
       x = "Accessible promoter (≤ 1 kb)") +
  theme_pubr() + 
  stat_compare_means(method = "wilcox.test", 
                     comparisons = list(c("TRUE", "FALSE")),
                     label = "p.format",
                     step.increase = 0.05) +
  theme(legend.position = "none") 



# Peaks in all genos is too conservative to compare against genes with no peaks
## Look at peaks found in at least one genotype
## 2nd: TRUE or FALSE for if peak is found in at least one genotype
union.peaks <- Reduce(union, x) # 10511

in.peaks.one.geno <- rownames(non.acc.expression.df) %in% union.peaks #  genes overlap

# Ground truth calls
true_genes <- non.acc.expression.df[in.peaks.one.geno , ]

# Assign TRUE/FALSE values based on presence in peaks.intersection.all.genos
non.acc.expression.df$one.geno <- in.peaks.one.geno

# Visualize
non.acc.expression.df$one.geno <- factor(non.acc.expression.df$one.geno)

# Log10 Base mean expression of genes with accessible promoters
expression <- ggplot(non.acc.expression.df, aes(x = one.geno, 
                                  y = log10bM, 
                                  fill = one.geno)) + 
  ggdist::stat_halfeye()+
  scale_fill_manual(values = c("#ccb7ae",
                               "#ada7c9")) +
  labs(title = "Expression of genes\nwith accessible and non-accessible promoters",
       x = "Accessible promoter (≤ 1 kb)") +
  theme_pubr() + 
  stat_compare_means(method = "wilcox.test",
                     comparisons = list(c("TRUE", "FALSE")),
                     label = "p.format",
                     step.increase = 0.05) +
  theme(legend.position = "none") 

# log2FC to heat stress of genes with accessible promoters

hs.l2fc <- ggplot(non.acc.expression.df, aes(x = one.geno, 
                                  y = log2FoldChange, 
                                  fill = one.geno)) + 
  ggdist::stat_halfeye()+
  scale_fill_manual(values = c("#ccb7ae",
                               "#ada7c9")) +
  labs(title = "Heat stress l2fc in genes\nwith accessible and non-accessible promoters",
       x = "Accessible promoter (≤ 1 kb)") +
  theme_pubr() + 
  stat_compare_means(method = "t.test", 
                     comparisons = list(c("TRUE", "FALSE")),
                     label = "p.format",
                     step.increase = 0.05) +
  theme(legend.position = "none")



# lfcSE of accessible promoters
expression.var <- ggplot(non.acc.expression.df, aes(x = one.geno, 
                                  y = lfcSE, 
                                  fill = one.geno)) +
  ggdist::stat_halfeye()+
  scale_fill_manual(values = c("#ccb7ae",
                               "#ada7c9")) +
  labs(title = "Expression variation of genes\nwith accessible and non-accessible promoters",
       x = "Accessible promoter (≤ 1 kb)") +
  theme_pubr() + 
  stat_compare_means(method = "wilcox.test", 
                     comparisons = list(c("TRUE", "FALSE")),
                     label = "p.format",
                     step.increase = 0.05) +
  theme(legend.position = "none") 
  
(hs.l2fc | (expression / expression.var))

# Look at relationship between distance to TSS and baseMean/lfcSE
### Check first if the distanceToTSS varies for each gene between the genotypes
geno.1.promoter$geno <- as.factor("1") 
geno.2.promoter$geno <- as.factor("2")
geno.3.promoter$geno <- as.factor("3") 
geno.4.promoter$geno <- as.factor("4")

geno1_density <- ggplot(geno.1.promoter, aes(x = distanceToTSS)) +
  geom_density(fill = "skyblue", alpha = 0.5) +
  labs(title = "Geno 1: Distance to TSS",
       x = "Distance to TSS",
       y = "Density") +
  theme_pubr()

geno2_density <- ggplot(geno.2.promoter, aes(x = distanceToTSS)) +
  geom_density(fill = "skyblue", alpha = 0.5) +
  labs(title = "Geno 2: Distance to TSS",
       x = "Distance to TSS",
       y = "Density") +
  theme_pubr()

geno3_density <- ggplot(geno.3.promoter, aes(x = distanceToTSS)) +
  geom_density(fill = "skyblue", alpha = 0.5) +
  labs(title = "Geno 3: Distance to TSS",
       x = "Distance to TSS",
       y = "Density") +
  theme_pubr()

geno4_density <- ggplot(geno.4.promoter, aes(x = distanceToTSS)) +
  geom_density(fill = "skyblue", alpha = 0.5) +
  labs(title = "Geno 4: Distance to TSS",
       x = "Distance to TSS",
       y = "Density") +
  theme_pubr()

(geno1_density + geno2_density) / (geno3_density + geno4_density)

# Modify data frame
non.acc.expression.df$distanceToTSS.geno1 <- geno.1.promoter$distanceToTSS[rownames(non.acc.expression.df)]
filtered_data <- non.acc.expression.df[!is.na(non.acc.expression.df$distanceToTSS.geno1), ]

# # Plot log2FoldChange against distanceToTSS.geno1
# ggplot(filtered_data, aes(x = distanceToTSS.geno1, y = log2FoldChange)) +
#   geom_point() +
#   labs(x = "Distance to TSS (geno1)", y = "log2FoldChange") +
#   theme_minimal()

# TopGO of peaks


# Looking at peaks in 2/4 individuals

geneID_geno1 <- unique(as.data.frame(geno.1.promoter$geneId))
colnames(geneID_geno1) <- "geneID"
geneID_geno2 <- unique(as.data.frame(geno.2.promoter$geneId))
colnames(geneID_geno2) <- "geneID"
geneID_geno3 <- unique(as.data.frame(geno.3.promoter$geneId))
colnames(geneID_geno3) <- "geneID"
geneID_geno4 <- unique(as.data.frame(geno.4.promoter$geneId))
colnames(geneID_geno4) <- "geneID"

geneID_1_2 <- dplyr::inner_join(geneID_geno1, geneID_geno2, by = "geneID")
geneID_1_3 <- dplyr::inner_join(geneID_geno1, geneID_geno3, by = "geneID")
geneID_1_4 <- dplyr::inner_join(geneID_geno1, geneID_geno4, by = "geneID")

geneID_2_3 <- dplyr::inner_join(geneID_geno2, geneID_geno3, by = "geneID")
geneID_2_4 <- dplyr::inner_join(geneID_geno2, geneID_geno4, by = "geneID")

geneID_3_4 <- dplyr::inner_join(geneID_geno3, geneID_geno4, by = "geneID")

geneID_2_outta_4 <- rbind(geneID_1_2, #362
                                 geneID_1_3, #179
                                 geneID_1_4, #278
                                 geneID_2_3, 
                                 geneID_2_4,
                                 geneID_3_4)

geneID_2_outta_4 <- unique(geneID_2_outta_4$geneID) #1741


in.peaks.two.genos <- rownames(non.acc.expression.df) %in% geneID_2_outta_4 #  genes overlap


# Assign TRUE/FALSE values based on presence in peaks.intersection.all.genos
non.acc.expression.df$two.genos <- in.peaks.two.genos

# Visualize
non.acc.expression.df$two.genos <- factor(non.acc.expression.df$two.genos )

# Log10 Base mean expression of genes with accessible promoters
expression <- ggplot(non.acc.expression.df, aes(x = two.genos, 
                                                y = log10bM, 
                                                fill = two.genos)) + 
  ggdist::stat_halfeye()+
  scale_fill_manual(values = c("#909580",
                               "#e7ad99")) +
  labs(title = "Expression of genes\nwith accessible and non-accessible promoters",
       x = "Accessible promoter (≤ 1 kb)") +
  theme_pubr() + 
  stat_compare_means(method = "wilcox.test",
                     comparisons = list(c("TRUE", "FALSE")),
                     label = "p.format",
                     step.increase = 0.05) +
  theme(legend.position = "none") 
expression
# log2FC to heat stress of genes with accessible promoters

hs.l2fc <- ggplot(non.acc.expression.df, aes(x = two.genos, 
                                             y = log2FoldChange, 
                                             fill = two.genos)) + 
  ggdist::stat_halfeye()+
  scale_fill_manual(values = c("#909580",
                               "#e7ad99")) +
  labs(title = "Heat stress l2fc in genes\nwith accessible and non-accessible promoters",
       x = "Accessible promoter (≤ 1 kb)") +
  theme_pubr() + 
  stat_compare_means(method = "t.test", 
                     comparisons = list(c("TRUE", "FALSE")),
                     label = "p.format",
                     step.increase = 0.05) +
  theme(legend.position = "none")
hs.l2fc 


# lfcSE of accessible promoters
expression.var <- ggplot(non.acc.expression.df, aes(x = one.geno, 
                                                    y = lfcSE, 
                                                    fill = one.geno)) +
  ggdist::stat_halfeye()+
  scale_fill_manual(values = c("#909580",
                               "#e7ad99")) +
  labs(title = "Expression variation of genes\nwith accessible and non-accessible promoters",
       x = "Accessible promoter (≤ 1 kb)") +
  theme_pubr() + 
  stat_compare_means(method = "wilcox.test", 
                     comparisons = list(c("TRUE", "FALSE")),
                     label = "p.format",
                     step.increase = 0.05) +
  theme(legend.position = "none") 
expression.var 
(hs.l2fc | (expression / expression.var))


# Contingency table of heat response genes and promoter accessibility:
total.gene.set <- read.csv('~/Lab Notebook/Chapter2/Data_analysis/TagSeq/Data_out/total.set.gene.names.csv', header = TRUE)

hrgs <- read.csv("~/Lab Notebook/Chapter2/Data_analysis/TagSeq/Data_out/HRG.csv", header = TRUE)
hrg.names <- data.frame(hrgs[,1])
colnames(hrg.names) <- colnames(hrgs)[1]

accessible.promoter.genes <-as.data.frame(geneID_2_outta_4)
colnames(accessible.promoter.genes) <- "gene"


# Count the overlap
overlap.count <- sum(hrg.names$gene %in% accessible.promoter.genes$gene)
print(overlap.count) #82

# Set up contingency table
total.genes <- nrow(total.gene.set)
HRG.count <- nrow(hrgs)
accessible.promoter.genes.count <- nrow(accessible.promoter.genes)
overlap.count <- overlap.count

# Create a 2x2 contingency table
contingency.table <- matrix(c(overlap.count, HRG.count - overlap.count,
                              accessible.promoter.genes.count - overlap.count,
                              total.genes - HRG.count - accessible.promoter.genes.count + overlap.count),
                            nrow = 2, ncol = 2, byrow = TRUE)

# Perform Fisher's exact test
result <- fisher.test(contingency.table)

# Extract p-value
p.value <- result$p.value

# Print the p-value
print(p.value)





## Back up and look at genic peaks


geno.1.genic.peaks <- filter(peaks.df.1, genic == "TRUE") # 4247

pValue_density_geno1 <- ggplot(geno.1.genic.peaks, aes(x = pValue)) +
  geom_density(fill = "skyblue", color = "blue") +
  labs(title = "Geno 1: Density of pValue", x = "pValue", y = "Density")


qValue_density_geno1 <- ggplot(geno.1.genic.peaks, aes(x = qValue)) +
  geom_density(fill = "lightgreen", color = "green") +
  labs(title = "Geno 1: Density of qValue", x = "qValue", y = "Density")

score_density_geno1 <- ggplot(geno.1.genic.peaks, aes(x = score)) +
  geom_density(fill = "violet", color = "purple") +
  labs(title = "Geno 1: Density of score", x = "score", y = "Density")

pValue_density_geno1 + qValue_density_geno1 + score_density_geno1

geno.2.genic.peaks <- filter(peaks.df.2, genic == "TRUE") # 10540 

pValue_density_geno2 <- ggplot(geno.2.genic.peaks, aes(x = pValue)) +
  geom_density(fill = "skyblue", color = "blue") +
  labs(title = "Geno 2: Density of pValue", x = "pValue", y = "Density")


qValue_density_geno2 <- ggplot(geno.2.genic.peaks, aes(x = qValue)) +
  geom_density(fill = "lightgreen", color = "green") +
  labs(title = "Geno 2: Density of qValue", x = "qValue", y = "Density")

score_density_geno2 <- ggplot(geno.2.genic.peaks, aes(x = score)) +
  geom_density(fill = "violet", color = "purple") +
  labs(title = "Geno 2: Density of score", x = "score", y = "Density")

pValue_density_geno2 + qValue_density_geno2 + score_density_geno2

geno.3.genic.peaks <- filter(peaks.df.3, genic == "TRUE") # 1274

pValue_density_geno3 <- ggplot(geno.3.genic.peaks, aes(x = pValue)) +
  geom_density(fill = "skyblue", color = "blue") +
  labs(title = "Geno 3: Density of pValue", x = "pValue", y = "Density")


qValue_density_geno3 <- ggplot(geno.3.genic.peaks, aes(x = qValue)) +
  geom_density(fill = "lightgreen", color = "green") +
  labs(title = "Geno 3: Density of qValue", x = "qValue", y = "Density")

score_density_geno3 <- ggplot(geno.3.genic.peaks, aes(x = score)) +
  geom_density(fill = "violet", color = "purple") +
  labs(title = "Geno 3: Density of score", x = "score", y = "Density")

pValue_density_geno3 + qValue_density_geno3 + score_density_geno3

geno.4.genic.peaks <- filter(peaks.df.4, genic == "TRUE") # 3080

pValue_density_geno4 <- ggplot(geno.4.genic.peaks, aes(x = pValue)) +
  geom_density(fill = "skyblue", color = "blue") +
  labs(title = "Geno 4: Density of pValue", x = "pValue", y = "Density")


qValue_density_geno4 <- ggplot(geno.4.genic.peaks, aes(x = qValue)) +
  geom_density(fill = "lightgreen", color = "green") +
  labs(title = "Geno 4: Density of qValue", x = "qValue", y = "Density")

# qValue_vs_pValue_geno4 <- ggplot(geno.4.genic.peaks, aes(x = qValue, y = pValue)) +
#   geom_point() +
#   labs(title = "qvalue vs pvalue", x = "qValue", y = "pValue")

score_density_geno4 <- ggplot(geno.4.genic.peaks, aes(x = score)) +
  geom_density(fill = "violet", color = "purple") +
  labs(title = "Geno 4: Density of score", x = "score", y = "Density")

# qValue_vs_score_geno4 <- ggplot(geno.4.genic.peaks, aes(x = qValue, y = score)) +
#   geom_point() +
#   labs(title = "qValue vs score", x = "qValue", y = "score")

pValue_density_geno4 + qValue_density_geno4 + score_density_geno4


# Venn Diagram 
pValue.threshold <- -log10(0.00005) # is this sufficiently conservative?

geno.1.genic.peaks <- filter(geno.1.genic.peaks, pValue >= pValue.threshold) 
genes.geno.1 <- unique(data.frame(gene = geno.1.genic.peaks$geneId)) 
genes.geno.1$geno<- as.factor("1")
dim(genes.geno.1) #3511


geno.2.genic.peaks <- filter(geno.2.genic.peaks, pValue >= pValue.threshold) 
genes.geno.2 <- unique(data.frame(gene = geno.2.genic.peaks$geneId))
genes.geno.2$geno<- as.factor("2")
dim(genes.geno.2) #13092

geno.3.genic.peaks <- filter(geno.3.genic.peaks, pValue >= pValue.threshold) #759 promoters with peak score greater than the first quartile
genes.geno.3 <- unique(data.frame(gene = geno.3.genic.peaks$geneId))
genes.geno.3$geno<- as.factor("3")
dim(genes.geno.3) #2299

geno.4.genic.peaks <- filter(geno.4.genic.peaks, pValue >= pValue.threshold) #1984 promoters with peak score greater than the first quartile
genes.geno.4 <- unique(data.frame(gene = geno.4.genic.peaks$geneId))
genes.geno.4$geno<- as.factor("4")
dim(genes.geno.4) #4849

x <- list(
  Geno_1 = genes.geno.1$gene, 
  Geno_2 = genes.geno.2$gene, 
  Geno_3 = genes.geno.3$gene,
  Geno_4 = genes.geno.4$gene
)
ggVennDiagram(x)

# Visualize

geneID_geno1 <- unique(as.data.frame(geno.1.genic.peaks$geneId))
colnames(geneID_geno1) <- "geneID"
geneID_geno2 <- unique(as.data.frame(geno.2.genic.peaks$geneId))
colnames(geneID_geno2) <- "geneID"
geneID_geno3 <- unique(as.data.frame(geno.3.genic.peaks$geneId))
colnames(geneID_geno3) <- "geneID"
geneID_geno4 <- unique(as.data.frame(geno.4.genic.peaks$geneId))
colnames(geneID_geno4) <- "geneID"

geneID_1_2 <- dplyr::inner_join(geneID_geno1, geneID_geno2, by = "geneID")
geneID_1_3 <- dplyr::inner_join(geneID_geno1, geneID_geno3, by = "geneID")
geneID_1_4 <- dplyr::inner_join(geneID_geno1, geneID_geno4, by = "geneID")

geneID_2_3 <- dplyr::inner_join(geneID_geno2, geneID_geno3, by = "geneID")
geneID_2_4 <- dplyr::inner_join(geneID_geno2, geneID_geno4, by = "geneID")

geneID_3_4 <- dplyr::inner_join(geneID_geno3, geneID_geno4, by = "geneID")

geneID_2_outta_4 <- rbind(geneID_1_2, #362
                          geneID_1_3, #179
                          geneID_1_4, #278
                          geneID_2_3, 
                          geneID_2_4,
                          geneID_3_4)

geneID_2_outta_4 <- unique(geneID_2_outta_4$geneID) #1741


in.peaks.two.genos <- rownames(non.acc.expression.df) %in% geneID_2_outta_4 #  genes overlap


# Assign TRUE/FALSE values based on presence in peaks.intersection.all.genos
non.acc.expression.df$two.genos <- in.peaks.two.genos

# Visualize
non.acc.expression.df$two.genos <- factor(non.acc.expression.df$two.genos )

# Log10 Base mean expression of genes with accessible promoters
expression <- ggplot(non.acc.expression.df, aes(x = two.genos, 
                                                y = log10bM, 
                                                fill = two.genos)) + 
  ggdist::stat_halfeye()+
  scale_fill_manual(values = c("#909580",
                               "#e7ad99")) +
  labs(title = "Expression of genes\nwith accessible and non-accessible promoters",
       x = "Genic Region Peak") +
  theme_pubr() + 
  stat_compare_means(method = "wilcox.test",
                     comparisons = list(c("TRUE", "FALSE")),
                     label = "p.format",
                     step.increase = 0.05) +
  theme(legend.position = "none") 
expression
# log2FC to heat stress of genes with accessible promoters

hs.l2fc <- ggplot(non.acc.expression.df, aes(x = two.genos, 
                                             y = log2FoldChange, 
                                             fill = two.genos)) + 
  ggdist::stat_halfeye()+
  scale_fill_manual(values = c("#909580",
                               "#e7ad99")) +
  labs(title = "Heat stress l2fc in genes\nwith accessible and non-accessible promoters",
       x = "Genic Region Peak") +
  theme_pubr() + 
  stat_compare_means(method = "t.test", 
                     comparisons = list(c("TRUE", "FALSE")),
                     label = "p.format",
                     step.increase = 0.05) +
  theme(legend.position = "none")
hs.l2fc 


# lfcSE of accessible promoters
expression.var <- ggplot(non.acc.expression.df, aes(x = one.geno, 
                                                    y = lfcSE, 
                                                    fill = one.geno)) +
  ggdist::stat_halfeye()+
  scale_fill_manual(values = c("#909580",
                               "#e7ad99")) +
  labs(title = "Expression variation of genes\nwith accessible and non-accessible promoters",
       x = "Genic Region Peak") +
  theme_pubr() + 
  stat_compare_means(method = "wilcox.test", 
                     comparisons = list(c("TRUE", "FALSE")),
                     label = "p.format",
                     step.increase = 0.05) +
  theme(legend.position = "none") 
expression.var 
(hs.l2fc | (expression / expression.var))



